---
title: "Formato de bases a .fst"
author: "Manuel Marcos"
format: html
---

```{r Configuración inicial}

# Limpia el entorno de trabajo de R #
#-----------------------------------#

rm(list=ls()) 

options(scipen = 999)
# Configura las opciones globales para los chunks de código en un documento #
#---------------------------------------------------------------------------#

knitr::opts_chunk$set(echo=TRUE,      # Hace que el código del chunk se muestre en el documento final.
                      warning=FALSE,  # Suprime la visualización de advertencias generadas en el documento final.
                      message=FALSE)  # Evita que se muestren mensajes en el documento final.
```

```{r Librerías, message=FALSE, warning=FALSE}

library(foreign)    # Importar y exportar bases de spss
library(openxlsx)   # Facilita la lectura de archivos de Excel (".xls" y ".xlsx")
library(fst)        # Abre archivos ".fst, que son extremadamente rápidos para guardar y cargar grandes conjuntos de datos
library(tidyverse)  # Un conjunto de paquetes interrelacionados diseñados para análisis de datos


``` 

```{r Llamado de funciones}

source(url("https://raw.githack.com/Manumarc/Resultados-ENLA/main/funciones.R"))

```

```{r Bases de datos}

#========================================================================================================#
# Valores plausibles
#========================================================================================================#

pisa00_math <- read.spss("01 Bases/PISA2000_math.sav", to.data.frame = T)
pisa00_read <- read.spss("01 Bases/PISA2000_read.sav", to.data.frame = T) 
pisa00_scie <- read.spss("01 Bases/PISA2000_scie.sav", to.data.frame = T) 
pisa03 <- read.spss("01 Bases/PISA2003_pv.sav", to.data.frame = T)
pisa06 <- read.spss("01 Bases/PISA2006_pv.sav", to.data.frame = T) 
pisa09 <- read.spss("01 Bases/PISA2009_pv.sav", to.data.frame = T) 
pisa12 <- read.spss("01 Bases/PISA2012_pv.sav", to.data.frame = T) 
pisa15 <- read.spss("01 Bases/PISA2015_pv.sav", to.data.frame = T) 
pisaD17 <- read.spss("01 Bases/PISAD2017_pv.sav", to.data.frame = T)
pisa18 <- read.spss("01 Bases/PISA2018_pv.sav", to.data.frame = T) 
pisa22 <- read.spss("01 Bases/PISA2022_pv.sav", to.data.frame = T) 

#========================================================================================================#
# Cuestionario a estudiantes 
#========================================================================================================#

school00 <- read.spss("01 Bases/PISA2000_school.sav", to.data.frame = T) 
school03 <- read.spss("01 Bases/PISA2003_school.sav", to.data.frame = T) 
school06 <- read.spss("01 Bases/PISA2006_school.sav", to.data.frame = T) 
school09 <- read.spss("01 Bases/PISA2009_school.sav", to.data.frame = T) 
school12 <- read.spss("01 Bases/PISA2012_school.sav", to.data.frame = T) 
school15 <- read.spss("01 Bases/PISA2015_school.sav", to.data.frame = T) 
schoolD17 <- read.spss("01 Bases/PISAD2017_school.sav", to.data.frame = T)  
school18 <- read.spss("01 Bases/PISA2018_school.sav", to.data.frame = T)
school22 <- read.spss("01 Bases/PISA2022_school.sav", to.data.frame = T) 

```

```{r}

write.fst(pisa00_math, path = "01 Bases/pisa00_math.fst")
write.fst(pisa00_read, path = "01 Bases/pisa00_read.fst")
write.fst(pisa00_scie, path = "01 Bases/pisa00_scie.fst")

write.fst(pisa03, path = "01 Bases/pisa03_pv.fst")
write.fst(pisa06, path = "01 Bases/pisa06_pv.fst")
write.fst(pisa09, path = "01 Bases/pisa09_pv.fst")
write.fst(pisa12, path = "01 Bases/pisa12_pv.fst")
write.fst(pisa15, path = "01 Bases/pisa15_pv.fst")
write.fst(pisaD17, path = "01 Bases/pisa17_pv.fst")
write.fst(pisa18, path = "01 Bases/pisa18_pv.fst")
write.fst(pisa22, path = "01 Bases/pisa22_pv.fst")

```

```{r}

write.fst(school00, path = "01 Bases/pisa00_school.fst")
write.fst(school03, path = "01 Bases/pisa03_school.fst")
write.fst(school06, path = "01 Bases/pisa06_school.fst")
write.fst(school09, path = "01 Bases/pisa09_school.fst")
write.fst(school12, path = "01 Bases/pisa12_school.fst")
write.fst(school15, path = "01 Bases/pisa15_school.fst")
write.fst(schoolD17, path = "01 Bases/pisa17_schoo.fst")
write.fst(school18, path = "01 Bases/pisa18_school.fst")
write.fst(school22, path = "01 Bases/pisa22_school.fst")

```

```{r}

```

