---
title: "Cálculo de indicadores PISA"
author: "Manuel Marcos"
format: html
---

```{r Configuración inicial}

# Limpia el entorno de trabajo de R #
#-----------------------------------#

rm(list=ls()) 

options(scipen = 999)
# Configura las opciones globales para los chunks de código en un documento #
#---------------------------------------------------------------------------#

knitr::opts_chunk$set(echo=TRUE,      # Hace que el código del chunk se muestre en el documento final.
                      warning=FALSE,  # Suprime la visualización de advertencias generadas en el documento final.
                      message=FALSE)  # Evita que se muestren mensajes en el documento final.
```

```{r Librerías, message=FALSE, warning=FALSE}

library(foreign)    # Importar y exportar bases de spss
library(openxlsx)   # Facilita la lectura de archivos de Excel (".xls" y ".xlsx")
library(fst)        # Abre archivos ".fst, que son extremadamente rápidos para guardar y cargar grandes conjuntos de datos
library(tidyverse)  # Un conjunto de paquetes interrelacionados diseñados para análisis de datos
library(ggplot2)    # Para crear gráficos
library(ggtext)     # Extiende las capacidades de personalización de texto en gráficos creados con ggplot2
library(ggpubr)     # Proporciona funciones de alto nivel para crear gráficos de publicación con ggplot2
library(gt)         # Permite convertir data.tables en tablas con un formato bonito
library(survey)     # Permite analizar datos provenientes de muestras complejas
library(ggh4x)      # Permite mejorar la estética de los gráficos
library(legendry)   # Permite crear y posicionar leyendas personalizadas en gráficos
library(Hmisc)      # Herramientas para análisis de datos
library(ggridges)   # Extiende ggplot2 para crear gráficos de densidad por grupos
library(stringi)    # Permite manipulación de cadenas de texto
library(patchwork)  # Permite combinar gráficos
library(ggrepel)    # Permite crear etiquetas con distanciamiento automático 
library(scales)     # Permite editar tonos, formatos de número y texto
library(sanzo)      # Paleta de combinación de colores de Sanzo Wada
library(intsvy)     # Permite analizar los datos de PISA y otras International Large Scale Assessments
library(furrr)      # Permite realizar análisis paralelizado

``` 

```{r Llamado de funciones}

source(url("https://raw.githack.com/Manumarc/Resultados-ENLA/main/funciones.R"))
source(url("https://raw.githack.com/Manumarc/PISA_indicators/main/pisa_indicator.R"))

```

```{r Bases de datos}

#========================================================================================================#
# Bases de PISA 
#========================================================================================================#

pisa00 <- read.fst("01 Bases/pisa00_dep.fst") # 5 valores plausibles
pisa03 <- read.fst("01 Bases/pisa03_dep.fst") # 5 valores plausibles
pisa06 <- read.fst("01 Bases/pisa06_dep.fst") # 5 valores plausibles
pisa09 <- read.fst("01 Bases/pisa09_dep.fst") # 5 valores plausibles
pisa12 <- read.fst("01 Bases/pisa12_dep.fst") # 5 valores plausibles
pisa15 <- read.fst("01 Bases/pisa15_dep.fst") # 10 valores plausibles
pisa18 <- read.fst("01 Bases/pisa18_dep.fst") # 10 valores plausibles
pisa22 <- read.fst("01 Bases/pisa22_dep.fst") # 10 valores plausibles

```

```{r Notas metodológicas}

# NOTA: OECD señala que solo se puede comparar un dominio hacia atrás hasta el ciclo en que fue dominio mayor por primera vez:

#   Lectura: escala establecida en 2000. 
#   Matemática: escala establecida en 2003.
#   Ciencia: escala establecida en 2006.

# PISA 2000: Los países de Argentina, Chile y Perú terminaron la aplicación de la prueba en 2002, no obstante forma parte de los resultados oficiales.
# PISA 2006: Estados Unidos no reporta resultados para Lectura porque los datos fueron considerados inválidos debido a errores de impresión en los cuadernillos de preguntas. 
# PISA 2009: Costa Rica realizó la aplicación de la prueba en 2010, no obstante forma parte de los resultados oficiales. El territorio de "Miranda" de Venezuela participó en esta edición.
# PISA 2022: Paraguay y Guatemala realizaron la aplicación de la prueba en 2021 (PISA-D), no obstante forma parte de los resultados oficiales.

# Sobre el cálculo de promedios, el reporte de resultados de PISA señala que el promedio de OECD se calcula como la media aritmética simple de los valores estimados para los países. Para el caso del error estandar, este se calcula como un promedio no ponderado de estimadores independientes que es la raíz cuadrada de la sumatoria de los errores estandar al cuadrado, todo entre el número de países considerados.

# Los grupos de países para los vectores de OECD y LAC se tomarons de los reportes de resultados de PISA correspondientes a cada año.

# Los indicadores de rendimiento (niveles de logro) se definen de la siguiente manera para CIMA:

#   Alto rendimiento: corresponde a los nivel 5 y 6
#   Bajo rendimiento: corresponde a los niveles debajo del nivel 2 (es decir no incluye el nivel 2) 

```

# Cálculo de resultados

```{r Argumentos de función}

# Forma de cálculo individual #
#-----------------------------#

 # calcular_pisa(
 #        data = pisa06,
 #        anio = 2006,
 #        compet = "Read", #Read o Math o Scie
 #        calculo = "MP",   #MP o Niveles
 #        niv_estrat = "Nacional" # Nacional o Estratos
 #      )

```

```{r Cálculo de MP + niv. logro}

#==============================================================================#
# Preparación de bases de datos 2000-2022
#==============================================================================#

lista_bases <- list(pisa00, pisa03, pisa06, pisa09, pisa12, pisa15, pisa18, pisa22) %>% 
  set_names(c(2000, 2003, 2006, 2009, 2012, 2015, 2018, 2022)) 

vars_fijas <- c("CNT", "COUNTRY", "CNTSCHID", "CNTSTUID", "ESCS",
                "sex", "lengua", "quintil_escs", "financia", "area", "gestion")

lista_bases_v2 <- lista_bases %>%
  map(~ .x %>% select(any_of(vars_fijas),
                      matches("^PV\\d{1,2}(READ|MATH|SCIE)$"),
                      matches("^W_")))

#==============================================================================#
# Definición de años y competencias evaluadas
#==============================================================================#

compet_por_anio <- list(
  "2000" = "Read",
  "2003" = c("Read", "Math"),
  "2006" = c("Read", "Math", "Scie"),
  "2009" = c("Read", "Math", "Scie"),
  "2012" = c("Read", "Math", "Scie"),
  "2015" = c("Read", "Math", "Scie"),
  "2018" = c("Read", "Math", "Scie"),
  "2022" = c("Read", "Math", "Scie")
)

#==============================================================================#
# Paralelización
#==============================================================================#

options(future.globals.maxSize = 3*1024^3)  

plan(multisession, workers = 2)

resultados <- future_imap(
  lista_bases_v2,
  function(base, anio_chr) {
    
    calcular_seguro <- possibly(calcular_pisa, otherwise = NULL)
    
    anio <- as.integer(anio_chr)
    
    grid <- expand_grid(
      compet  = compet_por_anio[[anio_chr]],
      calculo = c("MP", "Niveles"),
      niv_estrat = c("Nacional","Estratos")
    )
    
    pmap(
      grid, function(compet, calculo, niv_estrat) {
        
        res <- calcular_seguro(
          data = base, anio = anio,
          compet = compet, 
          calculo = calculo, 
          niv_estrat = niv_estrat
        )
        
        if (is.null(res)) return(NULL)
        
        res %>% mutate(
          calculo = .env$calculo, 
          niv_estrat = .env$niv_estrat
        )
      }
    ) %>%
      bind_rows()
  },
  .options = furrr_options(
    seed      = TRUE,
    packages  = c("intsvy", "dplyr", "tidyr", "purrr", "stringr", "tibble","haven"),
    scheduling = Inf     # reparto dinámico: el worker que termina agarra la siguiente base
  )
) %>%
  bind_rows()

plan(sequential)
gc()

#==============================================================================#
# Guardar resultado
#==============================================================================#

resultados$fallos    # revisa esto antes de exportar
write.xlsx(resultados, file = "01 Bases/bd_logro_2000_2022.xlsx")

```

# Cálculo de recursos físicos

```{r Calculo de Recursos físicos}

#==============================================================================#
# Bases para refis (2009-2022)
#==============================================================================#

lista_bases_rf <- list(pisa09, pisa12, pisa15, pisa18, pisa22) %>%
  set_names(c(2009, 2012, 2015, 2018, 2022))

#==============================================================================#
# Paralelización
#==============================================================================#

options(future.globals.maxSize = 3*1024^3)
plan(multisession, workers = 2)

resultados_rf <- future_imap(
  lista_bases_rf,
  function(base, anio_chr) {

    calcular_seguro <- possibly(calcular_refis, otherwise = NULL)
    anio <- as.integer(anio_chr)

    map(
      c("Nacional", "Estratos"),
      function(niv_estrat) {
        res <- calcular_seguro(
          bd_datos   = base,
          anio       = anio,
          niv_estrat = niv_estrat,
          verbose    = TRUE        
        )
        if (is.null(res)) return(NULL)
        res 
      }
    ) %>%
      bind_rows()
  },
  .options = furrr_options(
    seed       = TRUE,
    packages   = c("intsvy", "dplyr", "tidyr", "purrr", "stringr", "tibble", "haven"),
    scheduling = Inf     
  )
) %>%
  bind_rows()

plan(sequential)
gc()

#==============================================================================#
# Guardar resultado
#==============================================================================#

write.xlsx(resultados_rf, file = "01 Bases/bd_rf_2009_2022.xlsx")

```

```{r}

```

